// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomepageDocumentDataSlicesSlice =
  | HeroSplitSlice
  | StatsRowSlice
  | ServiceBentoSlice
  | TextSectionSlice
  | CtaBandSlice
  | PageIntroSlice
  | SectionBlockSlice
  | ProjectGallerySlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Meta title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Homepage browser title
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Search snippet
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Homepage slice zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | HeroSplitSlice
  | StatsRowSlice
  | ServiceBentoSlice
  | TextSectionSlice
  | CtaBandSlice
  | PageIntroSlice
  | SectionBlockSlice
  | ProjectGallerySlice
  | CompanyEventsHeroSlice
  | CompanyEventsStoriesSlice
  | CompanyEventsMediaSlice
  | EditorialsHeroSlice
  | EditorialsStoriesSlice
  | CsrArticleHeroSlice
  | EditorialArticleBodySlice
  | EditorialArticleTableSlice
  | EditorialArticleGallerySlice
  | CsrArticleBodySlice
  | CsrArticleGallerySlice
  | ImageTextSectionSlice
  | GroupCeoFounderSlice
  | SolutionParallaxSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Meta title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Shown in browser tab and search
   * - **API ID Path**: page.meta_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Short summary for search snippets
   * - **API ID Path**: page.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Slice zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = HomepageDocument | PageDocument;

/**
 * Primary content in *CompanyEventsHero → Default → Primary*
 */
export interface CompanyEventsHeroSliceDefaultPrimary {
  /**
   * Eyebrow field in *CompanyEventsHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Company
   * - **API ID Path**: company_events_hero.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Heading field in *CompanyEventsHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: company_events_hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Subheading field in *CompanyEventsHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Corporate press & community stories
   * - **API ID Path**: company_events_hero.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheading: prismic.KeyTextField;

  /**
   * Banner image URL field in *CompanyEventsHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: https://...
   * - **API ID Path**: company_events_hero.default.primary.banner_image_url
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  banner_image_url: prismic.KeyTextField;

  /**
   * Banner alt text field in *CompanyEventsHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: company_events_hero.default.primary.banner_image_alt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  banner_image_alt: prismic.KeyTextField;
}

/**
 * Default variation for CompanyEventsHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CompanyEventsHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CompanyEventsHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CompanyEventsHero*
 */
type CompanyEventsHeroSliceVariation = CompanyEventsHeroSliceDefault;

/**
 * CompanyEventsHero Shared Slice
 *
 * - **API ID**: `company_events_hero`
 * - **Description**: Immersive hero for Company Events (image + headline). Edit in Prismic.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CompanyEventsHeroSlice = prismic.SharedSlice<
  "company_events_hero",
  CompanyEventsHeroSliceVariation
>;

/**
 * Primary content in *CompanyEventsMedia → Default → Primary*
 */
export interface CompanyEventsMediaSliceDefaultPrimary {
  /**
   * Eyebrow label field in *CompanyEventsMedia → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Media
   * - **API ID Path**: company_events_media.default.primary.section_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_label: prismic.KeyTextField;

  /**
   * Section heading field in *CompanyEventsMedia → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: company_events_media.default.primary.section_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_heading: prismic.RichTextField;

  /**
   * Intro field in *CompanyEventsMedia → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Lightning and security related news…
   * - **API ID Path**: company_events_media.default.primary.section_intro
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_intro: prismic.KeyTextField;
}

/**
 * Primary content in *CompanyEventsMedia → Items*
 */
export interface CompanyEventsMediaSliceDefaultItem {
  /**
   * Summary + outlet field in *CompanyEventsMedia → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: company_events_media.items[].blurb
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  blurb: prismic.KeyTextField;

  /**
   * Article URL field in *CompanyEventsMedia → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: https://...
   * - **API ID Path**: company_events_media.items[].external_url
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  external_url: prismic.KeyTextField;

  /**
   * Thumbnail URL field in *CompanyEventsMedia → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: https://...
   * - **API ID Path**: company_events_media.items[].thumbnail_url
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  thumbnail_url: prismic.KeyTextField;

  /**
   * Thumbnail alt field in *CompanyEventsMedia → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: company_events_media.items[].thumbnail_alt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  thumbnail_alt: prismic.KeyTextField;
}

/**
 * Default variation for CompanyEventsMedia Slice
 *
 * - **API ID**: `default`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CompanyEventsMediaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CompanyEventsMediaSliceDefaultPrimary>,
  Simplify<CompanyEventsMediaSliceDefaultItem>
>;

/**
 * Slice variation for *CompanyEventsMedia*
 */
type CompanyEventsMediaSliceVariation = CompanyEventsMediaSliceDefault;

/**
 * CompanyEventsMedia Shared Slice
 *
 * - **API ID**: `company_events_media`
 * - **Description**: External media coverage cards (outbound links). Managed in Prismic.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CompanyEventsMediaSlice = prismic.SharedSlice<
  "company_events_media",
  CompanyEventsMediaSliceVariation
>;

/**
 * Primary content in *CompanyEventsStories → Default → Primary*
 */
export interface CompanyEventsStoriesSliceDefaultPrimary {
  /**
   * Section label field in *CompanyEventsStories → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Press & community
   * - **API ID Path**: company_events_stories.default.primary.section_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_label: prismic.KeyTextField;

  /**
   * Section heading field in *CompanyEventsStories → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: company_events_stories.default.primary.section_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_heading: prismic.RichTextField;

  /**
   * Optional intro line field in *CompanyEventsStories → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: company_events_stories.default.primary.section_intro
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_intro: prismic.KeyTextField;
}

/**
 * Primary content in *CompanyEventsStories → Items*
 */
export interface CompanyEventsStoriesSliceDefaultItem {
  /**
   * Card title field in *CompanyEventsStories → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Short headline — shown prominently on the card
   * - **API ID Path**: company_events_stories.items[].card_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  card_title: prismic.KeyTextField;

  /**
   * Excerpt (body under title) field in *CompanyEventsStories → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: company_events_stories.items[].excerpt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  excerpt: prismic.KeyTextField;

  /**
   * Read more path field in *CompanyEventsStories → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: /csr_ambulance
   * - **API ID Path**: company_events_stories.items[].read_more_path
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  read_more_path: prismic.KeyTextField;

  /**
   * Thumbnail URL field in *CompanyEventsStories → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: https://...
   * - **API ID Path**: company_events_stories.items[].thumbnail_url
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  thumbnail_url: prismic.KeyTextField;

  /**
   * Thumbnail alt field in *CompanyEventsStories → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: company_events_stories.items[].thumbnail_alt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  thumbnail_alt: prismic.KeyTextField;

  /**
   * Optional badge field in *CompanyEventsStories → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: CSR · 2022
   * - **API ID Path**: company_events_stories.items[].badge
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  badge: prismic.KeyTextField;
}

/**
 * Default variation for CompanyEventsStories Slice
 *
 * - **API ID**: `default`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CompanyEventsStoriesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CompanyEventsStoriesSliceDefaultPrimary>,
  Simplify<CompanyEventsStoriesSliceDefaultItem>
>;

/**
 * Slice variation for *CompanyEventsStories*
 */
type CompanyEventsStoriesSliceVariation = CompanyEventsStoriesSliceDefault;

/**
 * CompanyEventsStories Shared Slice
 *
 * - **API ID**: `company_events_stories`
 * - **Description**: Press / CSR story cards linking to internal pages. Reorder or add rows in Prismic.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CompanyEventsStoriesSlice = prismic.SharedSlice<
  "company_events_stories",
  CompanyEventsStoriesSliceVariation
>;

/**
 * Primary content in *CsrArticleBody → Default → Primary*
 */
export interface CsrArticleBodySliceDefaultPrimary {
  /**
   * Optional lead paragraph field in *CsrArticleBody → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Shown above all sections
   * - **API ID Path**: csr_article_body.default.primary.intro
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  intro: prismic.KeyTextField;
}

/**
 * Primary content in *CsrArticleBody → Items*
 */
export interface CsrArticleBodySliceDefaultItem {
  /**
   * Section heading (optional) field in *CsrArticleBody → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: csr_article_body.items[].section_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_heading: prismic.KeyTextField;

  /**
   * Body field in *CsrArticleBody → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: csr_article_body.items[].body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for CsrArticleBody Slice
 *
 * - **API ID**: `default`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CsrArticleBodySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CsrArticleBodySliceDefaultPrimary>,
  Simplify<CsrArticleBodySliceDefaultItem>
>;

/**
 * Slice variation for *CsrArticleBody*
 */
type CsrArticleBodySliceVariation = CsrArticleBodySliceDefault;

/**
 * CsrArticleBody Shared Slice
 *
 * - **API ID**: `csr_article_body`
 * - **Description**: Article sections (optional heading + rich body per block). Reorder in Prismic.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CsrArticleBodySlice = prismic.SharedSlice<
  "csr_article_body",
  CsrArticleBodySliceVariation
>;

/**
 * Primary content in *CsrArticleGallery → Default → Primary*
 */
export interface CsrArticleGallerySliceDefaultPrimary {
  /**
   * Gallery heading field in *CsrArticleGallery → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Picture Gallery
   * - **API ID Path**: csr_article_gallery.default.primary.gallery_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  gallery_heading: prismic.KeyTextField;
}

/**
 * Primary content in *CsrArticleGallery → Items*
 */
export interface CsrArticleGallerySliceDefaultItem {
  /**
   * Image URL field in *CsrArticleGallery → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: https://...
   * - **API ID Path**: csr_article_gallery.items[].image_url
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  image_url: prismic.KeyTextField;

  /**
   * Alt text field in *CsrArticleGallery → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: csr_article_gallery.items[].image_alt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  image_alt: prismic.KeyTextField;
}

/**
 * Default variation for CsrArticleGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CsrArticleGallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CsrArticleGallerySliceDefaultPrimary>,
  Simplify<CsrArticleGallerySliceDefaultItem>
>;

/**
 * Slice variation for *CsrArticleGallery*
 */
type CsrArticleGallerySliceVariation = CsrArticleGallerySliceDefault;

/**
 * CsrArticleGallery Shared Slice
 *
 * - **API ID**: `csr_article_gallery`
 * - **Description**: Click-to-zoom image grid for the article.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CsrArticleGallerySlice = prismic.SharedSlice<
  "csr_article_gallery",
  CsrArticleGallerySliceVariation
>;

/**
 * Primary content in *CsrArticleHero → Default → Primary*
 */
export interface CsrArticleHeroSliceDefaultPrimary {
  /**
   * Eyebrow field in *CsrArticleHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Company Events
   * - **API ID Path**: csr_article_hero.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *CsrArticleHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: csr_article_hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Byline / attribution field in *CsrArticleHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: By Author Name, credentials (optional; editorials)
   * - **API ID Path**: csr_article_hero.default.primary.byline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  byline: prismic.KeyTextField;

  /**
   * Subtitle, date, or short dek field in *CsrArticleHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Separate from byline — e.g. publication date
   * - **API ID Path**: csr_article_hero.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheading: prismic.KeyTextField;

  /**
   * Background image URL field in *CsrArticleHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: https://... (optional)
   * - **API ID Path**: csr_article_hero.default.primary.banner_image_url
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  banner_image_url: prismic.KeyTextField;

  /**
   * Image alt field in *CsrArticleHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: csr_article_hero.default.primary.banner_image_alt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  banner_image_alt: prismic.KeyTextField;
}

/**
 * Default variation for CsrArticleHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CsrArticleHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CsrArticleHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CsrArticleHero*
 */
type CsrArticleHeroSliceVariation = CsrArticleHeroSliceDefault;

/**
 * CsrArticleHero Shared Slice
 *
 * - **API ID**: `csr_article_hero`
 * - **Description**: Dark immersive hero for CSR / event articles (matches Company Events).
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CsrArticleHeroSlice = prismic.SharedSlice<
  "csr_article_hero",
  CsrArticleHeroSliceVariation
>;

/**
 * Primary content in *CtaBand → Default → Primary*
 */
export interface CtaBandSliceDefaultPrimary {
  /**
   * Heading field in *CtaBand → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_band.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *CtaBand → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_band.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * CTA label field in *CtaBand → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_band.default.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_label: prismic.KeyTextField;

  /**
   * CTA path or URL field in *CtaBand → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: /contact
   * - **API ID Path**: cta_band.default.primary.cta_href
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_href: prismic.KeyTextField;

  /**
   * Aside image (optional) field in *CtaBand → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_band.default.primary.aside_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  aside_image: prismic.ImageField<never>;
}

/**
 * Default variation for CtaBand Slice
 *
 * - **API ID**: `default`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaBandSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaBandSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CtaBand*
 */
type CtaBandSliceVariation = CtaBandSliceDefault;

/**
 * CtaBand Shared Slice
 *
 * - **API ID**: `cta_band`
 * - **Description**: Dark CTA band with nested shell
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaBandSlice = prismic.SharedSlice<
  "cta_band",
  CtaBandSliceVariation
>;

/**
 * Primary content in *EditorialArticleBody → Default → Primary*
 */
export interface EditorialArticleBodySliceDefaultPrimary {
  /**
   * Lead / dek (optional) field in *EditorialArticleBody → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Shown once at top of this block
   * - **API ID Path**: editorial_article_body.default.primary.intro
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  intro: prismic.KeyTextField;
}

/**
 * Primary content in *EditorialArticleBody → Items*
 */
export interface EditorialArticleBodySliceDefaultItem {
  /**
   * Section heading (optional) field in *EditorialArticleBody → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: editorial_article_body.items[].section_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_heading: prismic.KeyTextField;

  /**
   * Body field in *EditorialArticleBody → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: editorial_article_body.items[].body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for EditorialArticleBody Slice
 *
 * - **API ID**: `default`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EditorialArticleBodySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EditorialArticleBodySliceDefaultPrimary>,
  Simplify<EditorialArticleBodySliceDefaultItem>
>;

/**
 * Slice variation for *EditorialArticleBody*
 */
type EditorialArticleBodySliceVariation = EditorialArticleBodySliceDefault;

/**
 * EditorialArticleBody Shared Slice
 *
 * - **API ID**: `editorial_article_body`
 * - **Description**: Long-form editorial prose (no card chrome). Stack multiple slices with Editorial article table for figures.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EditorialArticleBodySlice = prismic.SharedSlice<
  "editorial_article_body",
  EditorialArticleBodySliceVariation
>;

/**
 * Primary content in *EditorialArticleGallery → Default → Primary*
 */
export interface EditorialArticleGallerySliceDefaultPrimary {
  /**
   * Section heading field in *EditorialArticleGallery → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Product images
   * - **API ID Path**: editorial_article_gallery.default.primary.gallery_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  gallery_heading: prismic.KeyTextField;
}

/**
 * Primary content in *EditorialArticleGallery → Items*
 */
export interface EditorialArticleGallerySliceDefaultItem {
  /**
   * Image URL field in *EditorialArticleGallery → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: https://...
   * - **API ID Path**: editorial_article_gallery.items[].image_url
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  image_url: prismic.KeyTextField;

  /**
   * Alt text field in *EditorialArticleGallery → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: editorial_article_gallery.items[].image_alt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  image_alt: prismic.KeyTextField;
}

/**
 * Default variation for EditorialArticleGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EditorialArticleGallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EditorialArticleGallerySliceDefaultPrimary>,
  Simplify<EditorialArticleGallerySliceDefaultItem>
>;

/**
 * Slice variation for *EditorialArticleGallery*
 */
type EditorialArticleGallerySliceVariation =
  EditorialArticleGallerySliceDefault;

/**
 * EditorialArticleGallery Shared Slice
 *
 * - **API ID**: `editorial_article_gallery`
 * - **Description**: Stacked product/images for long-form editorials (click to enlarge).
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EditorialArticleGallerySlice = prismic.SharedSlice<
  "editorial_article_gallery",
  EditorialArticleGallerySliceVariation
>;

/**
 * Primary content in *EditorialArticleTable → Default → Primary*
 */
export interface EditorialArticleTableSliceDefaultPrimary {
  /**
   * Section heading above table (optional) field in *EditorialArticleTable → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. 2. Surge Protection Device (SPD)
   * - **API ID Path**: editorial_article_table.default.primary.section_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_heading: prismic.KeyTextField;

  /**
   * Table caption (optional) field in *EditorialArticleTable → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Screen readers / small print under table
   * - **API ID Path**: editorial_article_table.default.primary.caption
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  caption: prismic.KeyTextField;

  /**
   * First column header field in *EditorialArticleTable → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Parameter
   * - **API ID Path**: editorial_article_table.default.primary.column_one_header
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  column_one_header: prismic.KeyTextField;

  /**
   * Second column header field in *EditorialArticleTable → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Value
   * - **API ID Path**: editorial_article_table.default.primary.column_two_header
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  column_two_header: prismic.KeyTextField;
}

/**
 * Primary content in *EditorialArticleTable → Items*
 */
export interface EditorialArticleTableSliceDefaultItem {
  /**
   * Column 1 cell field in *EditorialArticleTable → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: editorial_article_table.items[].cell_one
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cell_one: prismic.KeyTextField;

  /**
   * Column 2 cell field in *EditorialArticleTable → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: editorial_article_table.items[].cell_two
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cell_two: prismic.KeyTextField;
}

/**
 * Default variation for EditorialArticleTable Slice
 *
 * - **API ID**: `default`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EditorialArticleTableSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EditorialArticleTableSliceDefaultPrimary>,
  Simplify<EditorialArticleTableSliceDefaultItem>
>;

/**
 * Slice variation for *EditorialArticleTable*
 */
type EditorialArticleTableSliceVariation = EditorialArticleTableSliceDefault;

/**
 * EditorialArticleTable Shared Slice
 *
 * - **API ID**: `editorial_article_table`
 * - **Description**: Two-column data table for specifications (optional section title and column headers).
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EditorialArticleTableSlice = prismic.SharedSlice<
  "editorial_article_table",
  EditorialArticleTableSliceVariation
>;

/**
 * Primary content in *EditorialsHero → Default → Primary*
 */
export interface EditorialsHeroSliceDefaultPrimary {
  /**
   * Eyebrow field in *EditorialsHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Insights
   * - **API ID Path**: editorials_hero.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Heading field in *EditorialsHero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: editorials_hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Subheading field in *EditorialsHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Technical editorials and design guidance
   * - **API ID Path**: editorials_hero.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheading: prismic.KeyTextField;

  /**
   * Background video URL (MP4) field in *EditorialsHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: /editorial_hero.mp4 or https://...
   * - **API ID Path**: editorials_hero.default.primary.background_video_url
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  background_video_url: prismic.KeyTextField;
}

/**
 * Default variation for EditorialsHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EditorialsHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EditorialsHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EditorialsHero*
 */
type EditorialsHeroSliceVariation = EditorialsHeroSliceDefault;

/**
 * EditorialsHero Shared Slice
 *
 * - **API ID**: `editorials_hero`
 * - **Description**: Immersive hero for the Editorials hub (matches Company Events styling).
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EditorialsHeroSlice = prismic.SharedSlice<
  "editorials_hero",
  EditorialsHeroSliceVariation
>;

/**
 * Primary content in *EditorialsStories → Default → Primary*
 */
export interface EditorialsStoriesSliceDefaultPrimary {
  /**
   * Section label field in *EditorialsStories → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Technical papers
   * - **API ID Path**: editorials_stories.default.primary.section_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_label: prismic.KeyTextField;

  /**
   * Section heading field in *EditorialsStories → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: editorials_stories.default.primary.section_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_heading: prismic.RichTextField;

  /**
   * Optional intro line field in *EditorialsStories → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: editorials_stories.default.primary.section_intro
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_intro: prismic.KeyTextField;
}

/**
 * Primary content in *EditorialsStories → Items*
 */
export interface EditorialsStoriesSliceDefaultItem {
  /**
   * Card title field in *EditorialsStories → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Short headline
   * - **API ID Path**: editorials_stories.items[].card_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  card_title: prismic.KeyTextField;

  /**
   * Excerpt field in *EditorialsStories → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: editorials_stories.items[].excerpt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  excerpt: prismic.KeyTextField;

  /**
   * Read more path field in *EditorialsStories → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: /tokaialras
   * - **API ID Path**: editorials_stories.items[].read_more_path
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  read_more_path: prismic.KeyTextField;

  /**
   * Thumbnail URL field in *EditorialsStories → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: https://...
   * - **API ID Path**: editorials_stories.items[].thumbnail_url
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  thumbnail_url: prismic.KeyTextField;

  /**
   * Thumbnail alt field in *EditorialsStories → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: editorials_stories.items[].thumbnail_alt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  thumbnail_alt: prismic.KeyTextField;

  /**
   * Optional badge field in *EditorialsStories → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: ALRAS · 2025
   * - **API ID Path**: editorials_stories.items[].badge
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  badge: prismic.KeyTextField;
}

/**
 * Default variation for EditorialsStories Slice
 *
 * - **API ID**: `default`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EditorialsStoriesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EditorialsStoriesSliceDefaultPrimary>,
  Simplify<EditorialsStoriesSliceDefaultItem>
>;

/**
 * Slice variation for *EditorialsStories*
 */
type EditorialsStoriesSliceVariation = EditorialsStoriesSliceDefault;

/**
 * EditorialsStories Shared Slice
 *
 * - **API ID**: `editorials_stories`
 * - **Description**: Editorial cards linking to article pages. Reorder or add rows in Prismic.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EditorialsStoriesSlice = prismic.SharedSlice<
  "editorials_stories",
  EditorialsStoriesSliceVariation
>;

/**
 * Primary content in *GroupCeoFounder → Default → Primary*
 */
export interface GroupCeoFounderSliceDefaultPrimary {
  /**
   * Eyebrow (optional) field in *GroupCeoFounder → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: group_ceo_founder.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Heading field in *GroupCeoFounder → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Group CEO / Founder’s Message
   * - **API ID Path**: group_ceo_founder.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *GroupCeoFounder → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: group_ceo_founder.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Portrait photo field in *GroupCeoFounder → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: group_ceo_founder.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for GroupCeoFounder Slice
 *
 * - **API ID**: `default`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GroupCeoFounderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GroupCeoFounderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *GroupCeoFounder*
 */
type GroupCeoFounderSliceVariation = GroupCeoFounderSliceDefault;

/**
 * GroupCeoFounder Shared Slice
 *
 * - **API ID**: `group_ceo_founder`
 * - **Description**: Group CEO / Founder letter — dark section, portrait image column, name pill. Use this instead of Image + text for the CEO message on About us.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GroupCeoFounderSlice = prismic.SharedSlice<
  "group_ceo_founder",
  GroupCeoFounderSliceVariation
>;

/**
 * Primary content in *HeroSplit → Default → Primary*
 */
export interface HeroSplitSliceDefaultPrimary {
  /**
   * Eyebrow field in *HeroSplit → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_split.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Heading field in *HeroSplit → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_split.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *HeroSplit → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_split.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Primary CTA label field in *HeroSplit → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_split.default.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_label: prismic.KeyTextField;

  /**
   * Primary CTA path or URL field in *HeroSplit → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: /contact
   * - **API ID Path**: hero_split.default.primary.cta_href
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_href: prismic.KeyTextField;

  /**
   * Secondary CTA label field in *HeroSplit → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_split.default.primary.secondary_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondary_label: prismic.KeyTextField;

  /**
   * Secondary CTA path or URL field in *HeroSplit → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: /services
   * - **API ID Path**: hero_split.default.primary.secondary_href
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondary_href: prismic.KeyTextField;

  /**
   * Hero image field in *HeroSplit → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_split.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for HeroSplit Slice
 *
 * - **API ID**: `default`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSplitSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSplitSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSplit*
 */
type HeroSplitSliceVariation = HeroSplitSliceDefault;

/**
 * HeroSplit Shared Slice
 *
 * - **API ID**: `hero_split`
 * - **Description**: Asymmetric split hero with optional image
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSplitSlice = prismic.SharedSlice<
  "hero_split",
  HeroSplitSliceVariation
>;

/**
 * Primary content in *ImageTextSection → Default → Primary*
 */
export interface ImageTextSectionSliceDefaultPrimary {
  /**
   * Eyebrow (optional) field in *ImageTextSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text_section.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Heading field in *ImageTextSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *ImageTextSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text_section.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Image field in *ImageTextSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Section layout field in *ImageTextSection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: auto
   * - **API ID Path**: image_text_section.default.primary.section_layout
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  section_layout: prismic.SelectField<"auto" | "founder_portrait", "filled">;

  /**
   * Video URL (optional MP4) field in *ImageTextSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: /mrt_section.mp4
   * - **API ID Path**: image_text_section.default.primary.video_url
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  video_url: prismic.KeyTextField;

  /**
   * Caption below image (optional) field in *ImageTextSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text_section.default.primary.image_caption
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  image_caption: prismic.KeyTextField;
}

/**
 * Default variation for ImageTextSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageTextSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageTextSectionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ImageTextSection → Full width video + glass card → Primary*
 */
export interface ImageTextSectionSliceFullWidthVideoPrimary {
  /**
   * Eyebrow (optional) field in *ImageTextSection → Full width video + glass card → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text_section.full_width_video.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Heading field in *ImageTextSection → Full width video + glass card → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text_section.full_width_video.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *ImageTextSection → Full width video + glass card → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_text_section.full_width_video.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Video URL (MP4) field in *ImageTextSection → Full width video + glass card → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: /mrt_section.mp4
   * - **API ID Path**: image_text_section.full_width_video.primary.video_url
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  video_url: prismic.KeyTextField;
}

/**
 * Full width video + glass card variation for ImageTextSection Slice
 *
 * - **API ID**: `full_width_video`
 * - **Description**: Edge-to-edge video background with frosted glass content card.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageTextSectionSliceFullWidthVideo = prismic.SharedSliceVariation<
  "full_width_video",
  Simplify<ImageTextSectionSliceFullWidthVideoPrimary>,
  never
>;

/**
 * Slice variation for *ImageTextSection*
 */
type ImageTextSectionSliceVariation =
  | ImageTextSectionSliceDefault
  | ImageTextSectionSliceFullWidthVideo;

/**
 * ImageTextSection Shared Slice
 *
 * - **API ID**: `image_text_section`
 * - **Description**: Two-column image + rich text section (used for About us / CSR-aligned layouts).
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageTextSectionSlice = prismic.SharedSlice<
  "image_text_section",
  ImageTextSectionSliceVariation
>;

/**
 * Primary content in *PageIntro → Default → Primary*
 */
export interface PageIntroSliceDefaultPrimary {
  /**
   * Eyebrow field in *PageIntro → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Solutions
   * - **API ID Path**: page_intro.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Heading field in *PageIntro → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_intro.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Intro field in *PageIntro → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_intro.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Optional CTA label field in *PageIntro → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_intro.default.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_label: prismic.KeyTextField;

  /**
   * Optional CTA path or URL field in *PageIntro → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_intro.default.primary.cta_href
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_href: prismic.KeyTextField;
}

/**
 * Default variation for PageIntro Slice
 *
 * - **API ID**: `default`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PageIntroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PageIntroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PageIntro*
 */
type PageIntroSliceVariation = PageIntroSliceDefault;

/**
 * PageIntro Shared Slice
 *
 * - **API ID**: `page_intro`
 * - **Description**: Inner page title band (no hero image)
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PageIntroSlice = prismic.SharedSlice<
  "page_intro",
  PageIntroSliceVariation
>;

/**
 * Primary content in *ProjectGallery → Items*
 */
export interface ProjectGallerySliceDefaultItem {
  /**
   * Section title field in *ProjectGallery → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: MRT Bukit Bintang
   * - **API ID Path**: project_gallery.items[].section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Image URL field in *ProjectGallery → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: https://...
   * - **API ID Path**: project_gallery.items[].image_url
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  image_url: prismic.KeyTextField;

  /**
   * Alt text field in *ProjectGallery → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project_gallery.items[].image_alt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  image_alt: prismic.KeyTextField;
}

/**
 * Default variation for ProjectGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectGallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ProjectGallerySliceDefaultItem>
>;

/**
 * Slice variation for *ProjectGallery*
 */
type ProjectGallerySliceVariation = ProjectGallerySliceDefault;

/**
 * ProjectGallery Shared Slice
 *
 * - **API ID**: `project_gallery`
 * - **Description**: Masonry gallery grouped by section title
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectGallerySlice = prismic.SharedSlice<
  "project_gallery",
  ProjectGallerySliceVariation
>;

/**
 * Primary content in *SectionBlock → Default → Primary*
 */
export interface SectionBlockSliceDefaultPrimary {
  /**
   * Heading field in *SectionBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_block.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *SectionBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_block.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for SectionBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SectionBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SectionBlockSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *SectionBlock → Items*
 */
export interface SectionBlockSlicePairCardsItem {
  /**
   * Card title field in *SectionBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_block.items[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *SectionBlock → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_block.items[].body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Card image (optional) field in *SectionBlock → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: section_block.items[].card_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  card_image: prismic.ImageField<never>;
}

/**
 * Primary content in *SectionBlock → Pair cards → Primary*
 */
export interface SectionBlockSlicePairCardsPrimary {
  /**
   * Section heading (optional) field in *SectionBlock → Pair cards → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_block.pair_cards.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading?: prismic.RichTextField;

  /**
   * Section intro (optional) field in *SectionBlock → Pair cards → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: section_block.pair_cards.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body?: prismic.RichTextField;
}

/**
 * Pair cards variation for SectionBlock Slice
 *
 * - **API ID**: `pair_cards`
 * - **Description**: Two-column grid of bordered cards (e.g. E&LP risk copy).
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SectionBlockSlicePairCards = prismic.SharedSliceVariation<
  "pair_cards",
  Simplify<SectionBlockSlicePairCardsPrimary>,
  Simplify<SectionBlockSlicePairCardsItem>
>;

/**
 * Slice variation for *SectionBlock*
 */
type SectionBlockSliceVariation =
  | SectionBlockSliceDefault
  | SectionBlockSlicePairCards;

/**
 * SectionBlock Shared Slice
 *
 * - **API ID**: `section_block`
 * - **Description**: H2 section with rich body
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SectionBlockSlice = prismic.SharedSlice<
  "section_block",
  SectionBlockSliceVariation
>;

/**
 * Primary content in *ServiceBento → Default → Primary*
 */
export interface ServiceBentoSliceDefaultPrimary {
  /**
   * Section heading field in *ServiceBento → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_bento.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Intro field in *ServiceBento → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_bento.default.primary.intro
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  intro: prismic.RichTextField;
}

/**
 * Primary content in *ServiceBento → Items*
 */
export interface ServiceBentoSliceDefaultItem {
  /**
   * Title field in *ServiceBento → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_bento.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *ServiceBento → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_bento.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Icon field in *ServiceBento → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: service_bento.items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon: prismic.SelectField<"lightning" | "shield" | "sun">;

  /**
   * Accent ring field in *ServiceBento → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: service_bento.items[].accent
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  accent: prismic.SelectField<"amber" | "slate">;
}

/**
 * Default variation for ServiceBento Slice
 *
 * - **API ID**: `default`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceBentoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiceBentoSliceDefaultPrimary>,
  Simplify<ServiceBentoSliceDefaultItem>
>;

/**
 * Slice variation for *ServiceBento*
 */
type ServiceBentoSliceVariation = ServiceBentoSliceDefault;

/**
 * ServiceBento Shared Slice
 *
 * - **API ID**: `service_bento`
 * - **Description**: Asymmetric 3-tile services grid
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceBentoSlice = prismic.SharedSlice<
  "service_bento",
  ServiceBentoSliceVariation
>;

/**
 * Primary content in *SolutionParallax → Items*
 */
export interface SolutionParallaxSliceDefaultItem {
  /**
   * Heading field in *SolutionParallax → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: solution_parallax.items[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *SolutionParallax → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: solution_parallax.items[].body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Image field in *SolutionParallax → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: solution_parallax.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * CTA label field in *SolutionParallax → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Learn more
   * - **API ID Path**: solution_parallax.items[].cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_label: prismic.KeyTextField;

  /**
   * CTA path field in *SolutionParallax → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: /elp-solutions
   * - **API ID Path**: solution_parallax.items[].cta_href
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_href: prismic.KeyTextField;
}

/**
 * Default variation for SolutionParallax Slice
 *
 * - **API ID**: `default`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SolutionParallaxSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<SolutionParallaxSliceDefaultItem>
>;

/**
 * Slice variation for *SolutionParallax*
 */
type SolutionParallaxSliceVariation = SolutionParallaxSliceDefault;

/**
 * SolutionParallax Shared Slice
 *
 * - **API ID**: `solution_parallax`
 * - **Description**: Sticky full-viewport solution panels (Our Solutions overview).
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SolutionParallaxSlice = prismic.SharedSlice<
  "solution_parallax",
  SolutionParallaxSliceVariation
>;

/**
 * Primary content in *StatsRow → Items*
 */
export interface StatsRowSliceDefaultItem {
  /**
   * Label field in *StatsRow → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stats_row.items[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Value field in *StatsRow → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stats_row.items[].value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  value: prismic.KeyTextField;
}

/**
 * Default variation for StatsRow Slice
 *
 * - **API ID**: `default`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StatsRowSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<StatsRowSliceDefaultItem>
>;

/**
 * Slice variation for *StatsRow*
 */
type StatsRowSliceVariation = StatsRowSliceDefault;

/**
 * StatsRow Shared Slice
 *
 * - **API ID**: `stats_row`
 * - **Description**: Three metrics in a ruled row
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StatsRowSlice = prismic.SharedSlice<
  "stats_row",
  StatsRowSliceVariation
>;

/**
 * Primary content in *TextSection → Default → Primary*
 */
export interface TextSectionSliceDefaultPrimary {
  /**
   * Heading field in *TextSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *TextSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_section.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for TextSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextSection*
 */
type TextSectionSliceVariation = TextSectionSliceDefault;

/**
 * TextSection Shared Slice
 *
 * - **API ID**: `text_section`
 * - **Description**: Editorial split text block
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSectionSlice = prismic.SharedSlice<
  "text_section",
  TextSectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      CompanyEventsHeroSlice,
      CompanyEventsHeroSliceDefaultPrimary,
      CompanyEventsHeroSliceVariation,
      CompanyEventsHeroSliceDefault,
      CompanyEventsMediaSlice,
      CompanyEventsMediaSliceDefaultPrimary,
      CompanyEventsMediaSliceDefaultItem,
      CompanyEventsMediaSliceVariation,
      CompanyEventsMediaSliceDefault,
      CompanyEventsStoriesSlice,
      CompanyEventsStoriesSliceDefaultPrimary,
      CompanyEventsStoriesSliceDefaultItem,
      CompanyEventsStoriesSliceVariation,
      CompanyEventsStoriesSliceDefault,
      CsrArticleBodySlice,
      CsrArticleBodySliceDefaultPrimary,
      CsrArticleBodySliceDefaultItem,
      CsrArticleBodySliceVariation,
      CsrArticleBodySliceDefault,
      CsrArticleGallerySlice,
      CsrArticleGallerySliceDefaultPrimary,
      CsrArticleGallerySliceDefaultItem,
      CsrArticleGallerySliceVariation,
      CsrArticleGallerySliceDefault,
      CsrArticleHeroSlice,
      CsrArticleHeroSliceDefaultPrimary,
      CsrArticleHeroSliceVariation,
      CsrArticleHeroSliceDefault,
      CtaBandSlice,
      CtaBandSliceDefaultPrimary,
      CtaBandSliceVariation,
      CtaBandSliceDefault,
      EditorialArticleBodySlice,
      EditorialArticleBodySliceDefaultPrimary,
      EditorialArticleBodySliceDefaultItem,
      EditorialArticleBodySliceVariation,
      EditorialArticleBodySliceDefault,
      EditorialArticleGallerySlice,
      EditorialArticleGallerySliceDefaultPrimary,
      EditorialArticleGallerySliceDefaultItem,
      EditorialArticleGallerySliceVariation,
      EditorialArticleGallerySliceDefault,
      EditorialArticleTableSlice,
      EditorialArticleTableSliceDefaultPrimary,
      EditorialArticleTableSliceDefaultItem,
      EditorialArticleTableSliceVariation,
      EditorialArticleTableSliceDefault,
      EditorialsHeroSlice,
      EditorialsHeroSliceDefaultPrimary,
      EditorialsHeroSliceVariation,
      EditorialsHeroSliceDefault,
      EditorialsStoriesSlice,
      EditorialsStoriesSliceDefaultPrimary,
      EditorialsStoriesSliceDefaultItem,
      EditorialsStoriesSliceVariation,
      EditorialsStoriesSliceDefault,
      GroupCeoFounderSlice,
      GroupCeoFounderSliceDefaultPrimary,
      GroupCeoFounderSliceVariation,
      GroupCeoFounderSliceDefault,
      HeroSplitSlice,
      HeroSplitSliceDefaultPrimary,
      HeroSplitSliceVariation,
      HeroSplitSliceDefault,
      ImageTextSectionSlice,
      ImageTextSectionSliceDefaultPrimary,
      ImageTextSectionSliceFullWidthVideoPrimary,
      ImageTextSectionSliceVariation,
      ImageTextSectionSliceDefault,
      ImageTextSectionSliceFullWidthVideo,
      PageIntroSlice,
      PageIntroSliceDefaultPrimary,
      PageIntroSliceVariation,
      PageIntroSliceDefault,
      ProjectGallerySlice,
      ProjectGallerySliceDefaultItem,
      ProjectGallerySliceVariation,
      ProjectGallerySliceDefault,
      SectionBlockSlice,
      SectionBlockSliceDefaultPrimary,
      SectionBlockSlicePairCardsItem,
      SectionBlockSlicePairCardsPrimary,
      SectionBlockSliceVariation,
      SectionBlockSliceDefault,
      SectionBlockSlicePairCards,
      ServiceBentoSlice,
      ServiceBentoSliceDefaultPrimary,
      ServiceBentoSliceDefaultItem,
      ServiceBentoSliceVariation,
      ServiceBentoSliceDefault,
      SolutionParallaxSlice,
      SolutionParallaxSliceDefaultItem,
      SolutionParallaxSliceVariation,
      SolutionParallaxSliceDefault,
      StatsRowSlice,
      StatsRowSliceDefaultItem,
      StatsRowSliceVariation,
      StatsRowSliceDefault,
      TextSectionSlice,
      TextSectionSliceDefaultPrimary,
      TextSectionSliceVariation,
      TextSectionSliceDefault,
    };
  }
}
